import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SanityClient, createClient } from "next-sanity";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const client:SanityClient = createClient();
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
